# Fichier docker-compose corrigé et commenté avec whiteboard lovasoa/wbo

services:
  # Site statique (HTML/CSS/JS)
  frida_web:
    build: ./frida/front-end
    ports:
      - "8080:80"

  # API PHP + Apache
  frida_api:
    build: ./frida/db
    depends_on:
      - frida_db
    environment:
      DB_HOST: frida_db
      DB_NAME: frida
      DB_USER: frida_user
      DB_PASSWORD: frida_pwd
    ports:
      - "8081:80"

  # Base de données MySQL pour l'API
  frida_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: frida
      MYSQL_USER: frida_user
      MYSQL_PASSWORD: frida_pwd
    volumes:
      - frida_db_data:/var/lib/mysql
      - ./frida/db/expo_frida.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # Nextcloud
  nextcloud:
    image: nextcloud
    ports:
      - "8082:80"
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - nextcloud_db
    environment:
      MYSQL_PASSWORD: nextcloud_pwd
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_HOST: nextcloud_db

  # Base de données MariaDB pour Nextcloud
  nextcloud_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: nextcloud_pwd
    volumes:
      - nextcloud_db_data:/var/lib/mysql

  # OnlyOffice pour édition collaborative
  onlyoffice:
    image: onlyoffice/documentserver
    depends_on:
      - nextcloud
    ports:
      - "8083:80"

  # Whiteboard : tableau blanc collaboratif (lovasoa/wbo)
  whiteboard:
    image: lovasoa/wbo
    ports:
      - "8084:80"

volumes:
  frida_db_data:
  nextcloud_data:
  nextcloud_db_data:
